name 'camptocamp-kmod'
version '0.1.1'
license 'Apache License, Version 2.0'
project_page 'https://github.com/camptocamp/puppet-kmod'
source       'https://github.com/camptocamp/puppet-kmod'
description 'Manage Linux kernel modules with Puppet'
summary 'Manage Linux kernel modules with Puppet'
